---
# Fileserver host variables for docker-01.home.stechsolutions.ca host

# other variables are set in group_vars/proxmox_vms.yaml and
# proxmox_vms/docker_hosts.yaml

fileserver_setup: true
fileserver_setup_nfs_client: true
fileserver_setup_attached_disks: true

fileserver_attached_disks:
  # 20 GB disk for docker compose downloader volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi1
    partition_label: 20-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/downloader"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted
  # 10 GB disk for docker compose proxy volume
  - name: scsi-0QEMU_QEMU_HARDDISK_drive-scsi2
    partition_label: 10-GB-VD-0
    mount_point: "/home/{{ default_user }}/docker_mounts/proxy"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
    filesystem_type: ext4
    options: defaults,errors=remount-ro
    state: mounted

fileserver_nfs_mounts:
  - path: /mnt/nfs/downloads
    server: storage.home.stechsolutions.ca
    nfs_export: /export/downloads
    docker_nfs_unit: mnt-nfs-downloads.mount
    options: defaults,_netdev
    state: mounted
  - path: /mnt/nfs/movies
    server: storage.home.stechsolutions.ca
    nfs_export: /export/movies
    docker_nfs_unit: mnt-nfs-movies.mount
    options: defaults,_netdev
    state: mounted
