---
http:
  routers:
    wrapperr-router:
      rule: Host(`media.stechsolutions.ca`) && PathPrefix(`/wrapperr`)
      entryPoints:
        - websecure
      service: wrapperr-service
      tls:
        certResolver: letsencrypt
      middlewares:
        - wrapperr-headers

  services:
    wrapperr-service:
      loadBalancer:
        servers:
          - url: https://wrapperr.home.stechsolutions.ca

  middlewares:
    wrapperr-headers:
      headers:
        customRequestHeaders:
          Host: wrapperr.home.stechsolutions.ca
